/* this file is generated automatically */

#ifndef __CSS_PROP_H__
#define __CSS_PROP_H__

#ifdef __cplusplus
extern "C" {
#endif
    
enum NCSSPROP {
	CSSID_BACKGROUND = 1,
	CSSID_BACKGROUND_ATTACHMENT = 2,
	CSSID_BACKGROUND_COLOR = 3,
	CSSID_BACKGROUND_IMAGE = 4,
	CSSID_BACKGROUND_POSITION = 5,
	CSSID_BACKGROUND_REPEAT = 6,
	CSSID_BORDER = 7,
	CSSID_BORDER_BOTTOM = 8,
	CSSID_BORDER_COLOR = 9,
	CSSID_BORDER_LEFT = 10,
	CSSID_BORDER_RIGHT = 11,
	CSSID_BORDER_STYLE = 12,
	CSSID_BORDER_TOP = 13,
	CSSID_CLEAR = 14,
	CSSID_COLOR = 15,
	CSSID_DISPLAY = 16,
	CSSID_FLOAT = 17,
	CSSID_FONT_SIZE = 18,
	CSSID_FONT_WEIGHT = 19,
	CSSID_HEIGHT = 20,
	CSSID_LINE_HEIGHT = 21,
	CSSID_MARGIN = 22,
	CSSID_MARGIN_BOTTOM = 23,
	CSSID_MARGIN_LEFT = 24,
	CSSID_MARGIN_RIGHT = 25,
	CSSID_MARGIN_TOP = 26,
	CSSID_MAX_WIDTH = 27,
	CSSID_OPACITY = 28,
	CSSID_OVERFLOW = 29,
	CSSID_PADDING = 30,
	CSSID_PADDING_BOTTOM = 31,
	CSSID_PADDING_LEFT = 32,
	CSSID_PADDING_RIGHT = 33,
	CSSID_PADDING_TOP = 34,
	CSSID_TEXT_ALIGN = 35,
	CSSID_TEXT_DECORATION = 36,
	CSSID_TEXT_INDENT = 37,
	CSSID_VERTICAL_ALIGN = 38,
	CSSID_WIDTH = 39,
	CSSID_Z_INDEX = 40,
	CSSID_LAST = 40
};

#define MAX_CSS_PROP_LEN	21

void css_initProp(void);
void css_delProp(void);
const char** css_getPropNames(void);

#ifdef __cplusplus
}
#endif

#endif
