/* this file is generated automatically */

#ifndef __XML_ATTS_H__
#define __XML_ATTS_H__

#ifdef __cplusplus
extern "C" {
#endif

enum ATTS {
	ATTID_ACTION = 1,
	ATTID_ALIGN = 2,
	ATTID_ALT = 3,
	ATTID_BGCOLOR = 4,
	ATTID_BORDER = 5,
	ATTID_CELLPADDING = 6,
	ATTID_CELLSPACING = 7,
	ATTID_CHARSET = 8,
	ATTID_CHECKED = 9,
	ATTID_CLASS = 10,
	ATTID_COLOR = 11,
	ATTID_COLS = 12,
	ATTID_CONTENT = 13,
	ATTID_DISABLED = 14,
	ATTID_ENCTYPE = 15,
	ATTID_HEIGHT = 16,
	ATTID_HREF = 17,
	ATTID_HTTP_EQUIV = 18,
	ATTID_ID = 19,
	ATTID_MAXLENGTH = 20,
	ATTID_METHOD = 21,
	ATTID_MULTIPLE = 22,
	ATTID_NAME = 23,
	ATTID_NE_DISPLAY = 24,
	ATTID_ONPICK = 25,
	ATTID_ONTIMER = 26,
	ATTID_READONLY = 27,
	ATTID_ROWS = 28,
	ATTID_SELECTED = 29,
	ATTID_SELECTED_P = 30,
	ATTID_SIZE = 31,
	ATTID_SRC = 32,
	ATTID_STYLE = 33,
	ATTID_TC_CUTEOFFSETX = 34,
	ATTID_TC_CUTEORIGINW = 35,
	ATTID_TC_FILENAME = 36,
	ATTID_TC_IA = 37,
	ATTID_TC_ISADS = 38,
	ATTID_TC_MAINTOPIC = 39,
	ATTID_TC_NAME = 40,
	ATTID_TC_NIDX = 41,
	ATTID_TC_ONFOCUS = 42,
	ATTID_TC_PCLIP = 43,
	ATTID_TC_RECT = 44,
	ATTID_TC_SEGMENT = 45,
	ATTID_TITLE = 46,
	ATTID_TYPE = 47,
	ATTID_URL = 48,
	ATTID_VALUE = 49,
	ATTID_WIDTH = 50,
	ATTID_LASTATT = 50
};

void xml_initAtts(void);
void xml_delAtts(void);
const char** xml_getAttNames(void);

#ifdef __cplusplus
}
#endif

#endif
